### ISSUE TITLE
undefined local variable or method `plural_cache`

### ISSUE THREAD

**Issue by crystalneth** [imgix/paperclip-imgix#4]
After installing the gem from github directly, I get this error upon calling the attachment url method.

I'm on Rails 3.2.12 and Paperclip 3.5.4

Trace:

```
1.9.3p429 :002 > p.photo.url
NameError: undefined local variable or method `plural_cache' for Paperclip::Imgix::Interpolations:Module
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/gems/paperclip-3.5.4/lib/paperclip/interpolations.rb:88:in `class'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:16:in `block (2 levels) in interpolate'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:15:in `gsub'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:15:in `block in interpolate'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:14:in `each'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:14:in `inject'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:14:in `interpolate'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/gems/paperclip-3.5.4/lib/paperclip/attachment.rb:455:in `interpolate'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/gems/paperclip-3.5.4/lib/paperclip/attachment.rb:165:in `path'
  from /Users/alex/Development/app/app/models/photo.rb:100:in `block in <class:Photo>'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:16:in `block (2 levels) in interpolate'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:15:in `gsub'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:15:in `block in interpolate'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:14:in `each'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:14:in `inject'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/interpolations.rb:14:in `interpolate'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/gems/paperclip-3.5.4/lib/paperclip/url_generator.rb:13:in `for'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/bundler/gems/paperclip-imgix-7435ad69c7ea/lib/paperclip-imgix/url_generator.rb:10:in `for'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/gems/paperclip-3.5.4/lib/paperclip/attachment.rb:149:in `url'
  from (irb):2
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
  from /Users/alex/.rvm/gems/ruby-1.9.3-p429@app/gems/railties-3.2.12/lib/rails/commands.rb:41:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'1.9.3p429 :003 > 
```

**Comment by kellysutton** [comment]
Unfortunately, this library is no longer maintained. We're looking for better ways of hooking into Paperclip that is more future-proof than this gem. As a result, we're cleaning up this repo and closing all old tickets.

We do have a lighter-weight gem for building and signing imgix URLs, which works well in tandem with normal paperclip. Please check that out here: https://github.com/imgix/imgix-rb
